name: Generate Snake

on:
  schedule: # run automatically every 24 hours
    - cron: "0 0 * * *"
  workflow_dispatch: # allow manual run

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate Snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: bdaanoun
          outputs: dist/snake.svg

      - name: Push snake.svg to output branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: dist
